### ISSUE TITLE
can it be uitextfield dependent ?

### ISSUE THREAD

**Issue by emadhegab** [efremidze/LEAmountInputView#1]
I didn't revised the code of that pod .. but I tried the demo and it's cool.. but it would be nicer if I can be able to depend on UITextField Instead of giving it just UIView .

**Comment by efremidze** [comment]
Are you saying displaying the numpad in the keyboard input view, enabled by selecting the textfield?

**Comment by emadhegab** [comment]
yup.. so instead of just adding the whole thing as subview.. i should give it the textfield as parameter and the textfield have the same format as your view

**Comment by efremidze** [comment]
Ya I can make a UITextField category

**Comment by emadhegab** [comment]
that would be awesome

**Comment by efremidze** [comment]
Try out the UITextField branch

**Comment by efremidze** [comment]
I'm adding documentation to the new changes. Once thats done, i'll merge it into master.

**Comment by emadhegab** [comment]
great
