### ISSUE TITLE
iOS 10 button highlight

### ISSUE THREAD

**Issue by jeffleeismyhero** [efremidze/LEAmountInputView#3]
In iOS 10, buttons remain highlighted after the click.

**Comment by efremidze** [comment]
Ill try to reproduce and fix it. Thanks!

**Comment by efremidze** [comment]
I tested on a couple of devices and I'm not seeing any issues.

**Comment by jeffleeismyhero** [comment]
Thanks, Lasha. You're right, there is no issue in this library.

The issue was with a UIButton category loaded by another library.
